name: Release Compiled PDF 
on:
  push:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./resume.pdf
